
DROP TABLE IF EXISTS dish;

CREATE TABLE dish
(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    vegetarian BOOLEAN NOT NULL,
    calories INT NOT NULL,
    type ENUM('MEAT', 'FISH', 'OTHER'),
    PRIMARY KEY(id)
);